const VERSION = 'v5';
const CACHE = `cardio-timer-${VERSION}`;
const ARCHIVOS = [
  './',
  './index.html',
  './styles.css',
  './manifest.json',
  './js/app.js',
  './js/editor.js',
  './js/ejecucion.js',
  './js/format.js',
  './js/frases.js',
  './js/storage.js',
  './js/version.js',
  './js/timer.js',
  './js/voice.js',
  './js/workout.js',
  './icons/apple-touch-icon.png',
  './icons/icon-192.png',
  './icons/icon-512.png'
];
const AUDIO = [
  './audio/n0.mp3',
  './audio/n1.mp3',
  './audio/n2.mp3',
  './audio/n3.mp3',
  './audio/n4.mp3',
  './audio/n5.mp3',
  './audio/n6.mp3',
  './audio/n7.mp3',
  './audio/n8.mp3',
  './audio/n9.mp3',
  './audio/n10.mp3',
  './audio/n11.mp3',
  './audio/n12.mp3',
  './audio/n13.mp3',
  './audio/n14.mp3',
  './audio/n15.mp3',
  './audio/n16.mp3',
  './audio/n17.mp3',
  './audio/n18.mp3',
  './audio/n19.mp3',
  './audio/n20.mp3',
  './audio/n21.mp3',
  './audio/n22.mp3',
  './audio/n23.mp3',
  './audio/n24.mp3',
  './audio/n25.mp3',
  './audio/n26.mp3',
  './audio/n27.mp3',
  './audio/n28.mp3',
  './audio/n29.mp3',
  './audio/n30.mp3',
  './audio/n31.mp3',
  './audio/n32.mp3',
  './audio/n33.mp3',
  './audio/n34.mp3',
  './audio/n35.mp3',
  './audio/n36.mp3',
  './audio/n37.mp3',
  './audio/n38.mp3',
  './audio/n39.mp3',
  './audio/n40.mp3',
  './audio/n41.mp3',
  './audio/n42.mp3',
  './audio/n43.mp3',
  './audio/n44.mp3',
  './audio/n45.mp3',
  './audio/n46.mp3',
  './audio/n47.mp3',
  './audio/n48.mp3',
  './audio/n49.mp3',
  './audio/n50.mp3',
  './audio/n51.mp3',
  './audio/n52.mp3',
  './audio/n53.mp3',
  './audio/n54.mp3',
  './audio/n55.mp3',
  './audio/n56.mp3',
  './audio/n57.mp3',
  './audio/n58.mp3',
  './audio/n59.mp3',
  './audio/n60.mp3',
  './audio/n61.mp3',
  './audio/n62.mp3',
  './audio/n63.mp3',
  './audio/n64.mp3',
  './audio/n65.mp3',
  './audio/n66.mp3',
  './audio/n67.mp3',
  './audio/n68.mp3',
  './audio/n69.mp3',
  './audio/n70.mp3',
  './audio/n71.mp3',
  './audio/n72.mp3',
  './audio/n73.mp3',
  './audio/n74.mp3',
  './audio/n75.mp3',
  './audio/n76.mp3',
  './audio/n77.mp3',
  './audio/n78.mp3',
  './audio/n79.mp3',
  './audio/n80.mp3',
  './audio/n81.mp3',
  './audio/n82.mp3',
  './audio/n83.mp3',
  './audio/n84.mp3',
  './audio/n85.mp3',
  './audio/n86.mp3',
  './audio/n87.mp3',
  './audio/n88.mp3',
  './audio/n89.mp3',
  './audio/n90.mp3',
  './audio/n91.mp3',
  './audio/n92.mp3',
  './audio/n93.mp3',
  './audio/n94.mp3',
  './audio/n95.mp3',
  './audio/n96.mp3',
  './audio/n97.mp3',
  './audio/n98.mp3',
  './audio/n99.mp3',
  './audio/n100.mp3',
  './audio/un.mp3',
  './audio/una.mp3',
  './audio/zona.mp3',
  './audio/por_ciento.mp3',
  './audio/segundo.mp3',
  './audio/segundos.mp3',
  './audio/minuto.mp3',
  './audio/minutos.mp3',
  './audio/hora.mp3',
  './audio/horas.mp3',
  './audio/descanso.mp3',
  './audio/calentamiento.mp3',
  './audio/enfriamiento.mp3',
  './audio/entreno_terminado.mp3'
];

self.addEventListener('install', (ev) => {
  ev.waitUntil(caches.open(CACHE).then((c) => c.addAll([...ARCHIVOS, ...AUDIO].map((u) => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (ev) => {
  ev.waitUntil(
    caches.keys()
      .then((claves) => Promise.all(claves.filter((k) => k.startsWith('cardio-timer-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (ev) => {
  if (ev.request.method !== 'GET') return;
  ev.respondWith(caches.match(ev.request, { ignoreSearch: true }).then((r) => r ?? fetch(ev.request)));
});
